# Sensor related parameters
mpu6050_sensor:
  ros__parameters:
    #FS_SEL  |  Full Scale Range
    #        |
    #   0    |  +- 250 deg/s
    #   1    |  +- 500 deg/s
    #   2    |  +- 1000 deg/s
    #   3    |  +- 2000 deg/s
    gyro_fs_sel: 0
    #FS_SEL  |  Full Scale Range
    #        |
    #   0    |  +- 2 g
    #   1    |  +- 4 g
    #   2    |  +- 8 g
    #   3    |  +- 16 g
    accel_afs_sel: 0
    #DLPF_CFG  |  Accelerometer    |            Gyroscope
    #          |    (Fs=1khz)      |
    #          |    Bandwidth(Hz)  |     Bandwidth(Hz)   |      Fs(khz)
    #   0      |       260         |         256         |        8
    #   1      |       184         |         188         |        1
    #   2      |       94          |         98          |        1
    #   3      |       44          |         42          |        1
    #   4      |       21          |         20          |        1
    #   5      |       10          |         10          |        1
    #   6      |       5           |         5           |        1
    dlpf_cfg: 0
    #CLKSEL  |  Clock source
    #        |
    #   0    |  Internal 8MHz oscillator
    #   1    |  PLL with X axis gyroscope reference
    #   2    |  PLL with Y axis gyroscope reference
    #   3    |  PLL with Z axis gyroscope reference
    #   4    |  PLL with external 32.768kHz reference
    #   5    |  PLL with external 19.2MHz reference
    #   6    |  Reserved
    #   7    |  Stops the clock and keeps the timing generator in reset
    clock_src: 0

    # [deg/s]
    gyro_x_offset: 4.59203
    gyro_y_offset: -1.1306
    gyro_z_offset: 1.44649
    # [m/sÂ²]
    accel_x_offset: 19.6194
    accel_y_offset: -9.73141
    accel_z_offset: 10.7192
